import { readdirSync, readFileSync, existsSync, statSync } from "node:fs";
import path from "node:path";

export type Agent = string;

export type Origin = "skyboy" | "vendor" | "community";
export type Badge = "official" | "vendor" | "verified" | "community";

// v2 skill shape (docs/skill-spec.md §6). The site reads the skills/ tree
// directly (source of truth) but exposes the same display contract the compact
// index records use: name, description, category, badge, version, permissions.
// License, author, upstream repo, and permissions detail come from
// metadata.json, read here at build time (no runtime cost).
// Computed fields (token_cost, router_description, quality, last_verified, stale,
// dependencies, compatibility, dup_of, dup_similarity, trust, trust_reason,
// trust_next, trust_missing, effectiveness) are read from the meta.json shard
// generated by build-catalog.
export interface Skill {
  id: string; // bare slug (skyboy) or @owner/slug
  slug: string; // last segment of id; equals the folder name
  owner: string | null; // the @owner namespace, when scoped
  category: string;
  name: string; // == slug: one name, ever (spec §1)
  description: string;
  tags: string[];
  compatibleAgents: Agent[];
  license: string;
  author: string;
  origin: Origin;
  verified: boolean;
  badge: Badge; // derived from origin + verified, stored nowhere
  version: string;
  permissions: {
    network: boolean;
    filesystem_write_outside_target: boolean;
    shell_exec: boolean;
    env_read: string[];
  };
  canonicalOf?: string | null;
  upstreamRepo?: string;
  path: string; // absolute skill folder path
  repoPath: string; // repo-relative, e.g. "skills/coding/@vercel/slug"
  // Model provider containers (skills/model-providers/<provider>/): a provider
  // is a model folder that carries its own SKILL.md plus nested skills/
  // sub-folders. `provider` is set on nested children (the provider
  // slug they live under); `isProvider` marks the container itself; the count
  // drives the browse card ("N skills").
  provider: string | null;
  isProvider: boolean;
  providerSkillCount: number;
  // Computed at ingest by build-catalog (read from meta.json shard):
  tokenCost?: number;
  routerDescription?: string;
  quality?: QualityReport;
  lastVerified?: string;
  stale?: boolean;
  dependencies?: string[];
  compatibility?: Record<string, CompatEntry>;
  dupOf?: string;
  dupSimilarity?: number;
  trust?: string;
  trustReason?: string;
  trustNext?: string;
  trustMissing?: string[];
  effectiveness?: Effectiveness;
}

// Lint-derived breakdown stored in the shard and shown on the skill page.
export interface QualityReport {
  score: number; // rounded 0-10 total
  triggerClarity: number; // 0-2.5
  scope: number; // 0-2.5
  links: number; // 0-2.5
  tokenBudget: number; // 0-2.5
  issues?: string[];
}

// One agent's tested state in the compatibility matrix.
export interface CompatEntry {
  toolSurface?: string; // e.g. "mcp-2025-06"; absent = untested
  notes?: string;
}

// Invocation-telemetry effectiveness summary.
export interface Effectiveness {
  invocations: number;
  successes: number;
  failures: number;
  score: number; // 0-1, Laplace-smoothed success rate
  confidence: number; // 0-1, how much evidence backs Score
}

// Metadata a skill's SKILL.md frontmatter officially declares (portable, shared
// with the agent that will consume it, separate from skyboy-only metadata.json).
// v2: name + description (+ optional license). compatible_agents moved out.
export interface SkillFrontmatter {
  name: string;
  description: string;
  license?: string;
}

// A bundled file (inside references/, scripts/, assets/) shown on the detail
// page alongside the SKILL.md preview.
export interface BundledFile {
  name: string; // e.g. "data-fetching.md"
  rel: string; // e.g. "references/data-fetching.md"
  size: number; // bytes
  kind: "reference" | "script" | "asset";
}

// Full detail for one skill, including the raw markdown + parsed body so the
// server component can render an in-page preview without a client round trip.
export interface SkillDetail extends Skill {
  skill: SkillFrontmatter; // frontmatter from SKILL.md
  body: string; // SKILL.md body without the frontmatter fence
  rawMarkdown: string; // full SKILL.md file contents
  files: BundledFile[];
  hasReferences: boolean;
  hasScripts: boolean;
  hasAssets: boolean;
}

interface RawMeta {
  id?: string;
  name?: string;
  category?: string;
  tags?: string[];
  compatible_agents?: string[];
  description?: string;
  command?: string;
  license?: string;
  author?: string;
  verified?: boolean;
  version?: string;
  origin?: Origin;
  source_type?: Origin; // v1 name, read for migration tolerance
  source_url?: string | null;
  upstream_repo?: string;
  canonical_of?: string | null;
  permissions?: Skill["permissions"];
  [key: string]: unknown;
}

function parseFrontmatter(contents: string): { name?: string; description?: string; [k: string]: string | undefined } {
  // \r?\n: Windows contributors commit CRLF; the fence must still parse.
  const m = contents.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  const out: { name?: string; description?: string; [k: string]: string | undefined } = {};
  if (!m) return out;
  for (const line of m[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const val = line.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
    if (key === "name") out.name = val;
    if (key === "description") out.description = val;
    if (key === "license") out.license = val;
  }
  return out;
}

// Split a SKILL.md into its frontmatter and the body below the closing fence.
function splitFrontmatter(contents: string): { fm: SkillFrontmatter; body: string } {
  const m = contents.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) {
    // No fence: treat the whole file as body, fall back to slug for name.
    return { fm: { name: "", description: "" }, body: contents };
  }
  return { fm: parseFrontmatter(m[0]) as SkillFrontmatter, body: contents.slice(m[0].length).trimStart() };
}

// Badge derivation (spec §4): origin + verified decide everything. Vendor is
// never a stronger trust signal than reviewed.
function badgeFrom(origin: Origin, verified: boolean): Badge {
  if (origin === "skyboy") return "official";
  if (origin === "vendor") return "vendor";
  return verified ? "verified" : "community";
}

function readSkill(skillDir: string, repoPath: string, provider: string | null = null): Skill | null {
  const skillPath = path.join(skillDir, "SKILL.md");
  const metaPath = path.join(skillDir, "skill.json");
  if (!existsSync(skillPath) || !existsSync(metaPath)) return null;

  const fm = parseFrontmatter(readFileSync(skillPath, "utf8"));
  const meta: RawMeta = JSON.parse(readFileSync(metaPath, "utf8"));

  // Identity: the folder name is the slug. A scoped folder nests under @owner/.
  const slug = path.basename(skillDir);
  const parent = path.basename(path.dirname(skillDir));
  const owner = parent.startsWith("@") ? parent.slice(1) : null;
  const id = owner ? `@${owner}/${slug}` : slug;

  const origin: Origin = meta.origin ?? meta.source_type ?? (meta.author === "skyboy" ? "skyboy" : "community");

  // A model-provider folder is a container (a "model" that holds skills),
  // not a leaf skill: skills/model-providers/<provider>/skills/….
  // Children under <provider>/skills/ come back with `provider` set.
  const nestedSkills = countChildSkillDirs(path.join(skillDir, "skills"));
  const isProvider = provider === null && (meta.category ?? "") === "model-providers";

  return {
    id,
    slug,
    owner,
    category: meta.category ?? "uncategorized",
    name: slug, // one name, ever (spec §1)
    description: meta.description ?? fm.description ?? "",
    tags: meta.tags ?? [],
    compatibleAgents: meta.compatible_agents ?? [],
    license: meta.license ?? "MIT",
    author: meta.author ?? owner ?? "skyboy",
    origin,
    verified: meta.verified ?? false,
    badge: badgeFrom(origin, meta.verified ?? false),
    version: meta.version ?? "1.0.0",
    permissions: meta.permissions ?? {
      network: false,
      filesystem_write_outside_target: false,
      shell_exec: false,
      env_read: [],
    },
    canonicalOf: meta.canonical_of ?? null,
    upstreamRepo: meta.source_url ?? meta.upstream_repo,
    path: skillDir,
    repoPath,
    provider,
    isProvider,
    providerSkillCount: isProvider ? nestedSkills : 0,
    // Read computed fields from meta.json shard (generated by build-catalog)
    ...readMetaShard(skillDir),
  };
}

// Read computed fields from the meta.json shard generated by build-catalog.
function readMetaShard(skillDir: string): Partial<Skill> {
  const metaPath = path.join(skillDir, "meta.json");
  if (!existsSync(metaPath)) return {};
  try {
    const raw = JSON.parse(readFileSync(metaPath, "utf8")) as Record<string, unknown>;
    return {
      tokenCost: raw.token_cost as number | undefined,
      routerDescription: raw.router_description as string | undefined,
      quality: raw.quality as QualityReport | undefined,
      lastVerified: raw.last_verified as string | undefined,
      stale: raw.stale as boolean | undefined,
      dependencies: raw.dependencies as string[] | undefined,
      compatibility: raw.compatibility as Record<string, CompatEntry> | undefined,
      dupOf: raw.dup_of as string | undefined,
      dupSimilarity: raw.dup_similarity as number | undefined,
      trust: raw.trust as string | undefined,
      trustReason: raw.trust_reason as string | undefined,
      trustNext: raw.trust_next as string | undefined,
      trustMissing: raw.trust_missing as string[] | undefined,
      effectiveness: raw.effectiveness as Effectiveness | undefined,
    };
  } catch {
    return {};
  }
}

// A child folder is a nested skill when it carries skill.json + SKILL.md.
// Counts are shallow (one level) — the container layout never nests deeper
// than provider/skills/<slug>.
function countChildSkillDirs(dir: string): number {
  if (!existsSync(dir)) return 0;
  let n = 0;
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory() && existsSync(path.join(full, "skill.json"))) n++;
  }
  return n;
}

// Content roots: the community-contributed skills/ tree that
// lives at the repo root. Overridable via SKYBOY_SKILLS_ROOT
// (for deploys that vendor the content elsewhere); the
// default walks up from the app dir to the repo root.
const REPO_ROOT = path.resolve(process.cwd(), "../..");
const SKILLS_ROOT = process.env.SKYBOY_SKILLS_ROOT
  ? path.resolve(process.env.SKYBOY_SKILLS_ROOT)
  : path.join(REPO_ROOT, "skills");

// Memoized catalog. listSkills() walks every folder under skills/; at four
// skills that is free, at hundreds of thousands it must happen exactly once per
// process (Next.js build or server start), never per page render.
let _skills: Skill[] | null = null;
let _plugins: Plugin[] | null = null;

// Walk skills/<category>/[<owner>/]<slug>/. The @owner level is exactly one
// deep (spec §1); anything deeper is ignored. Model providers are the one
// exception: a provider folder doubles as a container whose skills/ sub-level
// holds the provider's own skills (skills/model-providers/<p>/skills/<slug>/),
// indexed with `provider` set so browse can group them under the provider card.
function walkSkills(): Skill[] {
  if (!existsSync(SKILLS_ROOT)) return [];
  const skills: Skill[] = [];
  for (const category of readdirSync(SKILLS_ROOT)) {
    const catPath = path.join(SKILLS_ROOT, category);
    if (!existsSync(catPath) || !statSync(catPath).isDirectory()) continue;
    for (const entry of readdirSync(catPath)) {
      const entryPath = path.join(catPath, entry);
      if (!statSync(entryPath).isDirectory()) continue;
      if (entry.startsWith("@")) {
        for (const slug of readdirSync(entryPath)) {
          const skillDir = path.join(entryPath, slug);
          if (!statSync(skillDir).isDirectory()) continue;
          const skill = readSkill(skillDir, `skills/${category}/${entry}/${slug}`);
          if (skill) skills.push(skill);
        }
      } else {
        const skill = readSkill(entryPath, `skills/${category}/${entry}`);
        if (skill) skills.push(skill);
        if (skill?.isProvider) {
          const nestedRoot = path.join(entryPath, "skills");
          if (existsSync(nestedRoot) && statSync(nestedRoot).isDirectory()) {
            for (const slug of readdirSync(nestedRoot)) {
              const skillDir = path.join(nestedRoot, slug);
              if (!statSync(skillDir).isDirectory()) continue;
              const child = readSkill(
                skillDir,
                `skills/${category}/${entry}/skills/${slug}`,
                entry
              );
              if (child) skills.push(child);
            }
          }
        }
      }
    }
  }
  return skills;
}

export function listSkills(): Skill[] {
  if (_skills === null) _skills = walkSkills();
  return _skills;
}

// Model provider containers: the model-providers entries that hold skills.
// A provider is a model folder you open to find its skills, so browse
// renders it as a container card.
export function listProviders(): Skill[] {
  return listSkills().filter((s) => s.isProvider);
}

export function getProviderBySlug(slug: string): Skill | undefined {
  return listProviders().find((p) => p.slug === slug);
}

// The skills nested inside a provider (its skills/ folder).
export function getProviderSkills(providerSlug: string): Skill[] {
  return listSkills().filter((s) => s.provider === providerSlug);
}

// The dynamic category list (Part 4). Derived, never hardcoded: read from the
// generated catalog.json's categories key (which build-catalog derives from
// the skills/ tree), falling back to scanning the tree itself during local
// dev before catalog.json exists. Either way the sidebar renders whatever the
// catalog says, so a new category needs no code change.
export function getCategories(): string[] {
  const catalogPath = path.join(REPO_ROOT, "catalog.json");
  if (existsSync(catalogPath)) {
    try {
      const parsed = JSON.parse(readFileSync(catalogPath, "utf8")) as { categories?: string[] };
      if (Array.isArray(parsed.categories) && parsed.categories.length > 0) return parsed.categories;
    } catch {
      // Fall through to the filesystem scan.
    }
  }
  if (!existsSync(SKILLS_ROOT)) return [];
  return readdirSync(SKILLS_ROOT).filter((c) => {
    const p = path.join(SKILLS_ROOT, c);
    return existsSync(p) && statSync(p).isDirectory();
  });
}

const _byId = new Map<string, Skill>();
function byId(id: string): Skill | undefined {
  if (_byId.size === 0) for (const s of listSkills()) _byId.set(s.id, s);
  return _byId.get(id);
}

export function getSkillById(id: string): Skill | undefined {
  return byId(id);
}

export function getSkillBySlug(slug: string): Skill | undefined {
  // Slugs are unique across the catalog only within their id namespace; a bare
  // lookup matches bare ids first, then the slug part of scoped ids.
  const direct = byId(slug);
  if (direct) return direct;
  return listSkills().find((s) => s.slug === slug);
}

function listBundledFiles(skillDir: string): BundledFile[] {
  const out: BundledFile[] = [];
  for (const sub of ["references", "scripts", "assets"]) {
    const subPath = path.join(skillDir, sub);
    if (!existsSync(subPath) || !statSync(subPath).isDirectory()) continue;
    for (const name of readdirSync(subPath)) {
      const full = path.join(subPath, name);
      if (!statSync(full).isFile()) continue;
      out.push({ name, rel: `${sub}/${name}`, size: statSync(full).size, kind: sub === "references" ? "reference" : sub === "scripts" ? "script" : "asset" });
    }
  }
  return out;
}

export function getSkillDetail(idOrSlug: string): SkillDetail | null {
  const skill = getSkillBySlug(idOrSlug);
  if (!skill) return null;
  const rawMarkdown = readFileSync(path.join(skill.path, "SKILL.md"), "utf8");
  const { fm, body } = splitFrontmatter(rawMarkdown);
  const dirs = { references: false, scripts: false, assets: false };
  for (const sub of Object.keys(dirs) as (keyof typeof dirs)[]) {
    dirs[sub] = existsSync(path.join(skill.path, sub)) && statSync(path.join(skill.path, sub)).isDirectory();
  }
  return {
    ...skill,
    skill: { name: fm.name || skill.name, description: fm.description || skill.description, license: fm.license },
    body,
    rawMarkdown,
    files: listBundledFiles(skill.path),
    hasReferences: dirs.references,
    hasScripts: dirs.scripts,
    hasAssets: dirs.assets,
  };
}

// Every tag used across the catalog, deduped and sorted. Drives the tag filter.
export function getAllTags(): string[] {
  const set = new Set<string>();
  for (const s of listSkills()) for (const t of s.tags) set.add(t);
  return [...set].sort();
}

// Read a bundled file's contents so the detail page can show a syntax-highlighted
// view without exposing filesystem paths to the client.
export function readBundledFile(file?: {
  skillDir: string;
  rel: string;
}): string | null {
  if (!file) return null;
  const full = path.join(file.skillDir, file.rel);
  if (!existsSync(full) || !statSync(full).isFile()) return null;
  return readFileSync(full, "utf8");
}

export function getFeaturedSkills(): Skill[] {
  // Landing slot order: the four seed categories. Content quality > quantity.
  const all = listSkills();
  const order = [
    "nextjs-app-router-conventions",
    "anti-slop-landing",
    "context-window-management",
    "copy-self-audit",
  ];
  const bySlug = new Map(all.map((s) => [s.slug, s]));
  return order.map((slug) => bySlug.get(slug)).filter((s): s is Skill => Boolean(s));
}

export const SUPPORTED_AGENTS: { name: string; note: string; slug?: string }[] = [
  { name: "Claude Code", note: "AI coding", slug: "claude-code" },
  { name: "Claude Desktop", note: "AI assistant", slug: "claude-desktop" },
  { name: "Cursor", note: "AI coding", slug: "cursor" },
  { name: "ChatGPT", note: "AI assistant", slug: "chatgpt" },
  { name: "Gemini CLI", note: "AI coding", slug: "gemini-cli" },
  { name: "Codex CLI", note: "AI coding", slug: "codex-cli" },
  { name: "Windsurf", note: "AI coding", slug: "windsurf" },
  { name: "MCP", note: "tool protocol", slug: "mcp" },

  { name: "Anthropic", note: "AI models", slug: "anthropic" },
  { name: "OpenAI", note: "AI models", slug: "openai" },
  { name: "Meta", note: "open models", slug: "meta" },
  { name: "Zai", note: "AI models", slug: "zai" },
  { name: "xAI", note: "AI models", slug: "xai" },
  { name: "Kimi", note: "AI models", slug: "kimi" },
  { name: "Google", note: "AI models", slug: "google" },
  { name: "Alibaba Cloud", note: "AI models", slug: "alibaba-cloud" },
  { name: "DeepSeek", note: "AI models", slug: "deepseek" },
  { name: "MiniMax", note: "AI models", slug: "minimax" },
  { name: "Upstage", note: "AI models", slug: "upstage" },
  { name: "Multiverse Computing", note: "AI optimization", slug: "multiverse-computing" },
  { name: "Xiaomi", note: "AI models", slug: "xiaomi" },
  { name: "Thinking Machines", note: "AI research", slug: "thinking-machines" },
  { name: "InclusionAI", note: "AI models", slug: "inclusionai" },
  { name: "StepFun", note: "AI models", slug: "stepfun" },
  { name: "Mistral", note: "AI models", slug: "mistral" },
  { name: "Amazon Bedrock", note: "model platform", slug: "amazon-bedrock" },
  { name: "Cohere", note: "AI models", slug: "cohere" },
  { name: "Inception", note: "AI models", slug: "inception" },
  { name: "Arcee AI", note: "AI models", slug: "arcee-ai" },
  { name: "Liquid AI", note: "AI models", slug: "liquid-ai" },
  { name: "Microsoft Azure", note: "cloud platform", slug: "microsoft-azure" },
  { name: "Baseten", note: "model serving", slug: "baseten" },
  { name: "Databricks", note: "AI platform", slug: "databricks" },
];
